### ISSUE TITLE
Component/deployment lookup should use labels_selectors not resource names

### ISSUE THREAD

**Issue by TuxInvader** [TuxInvader/nginx-lb-operator#1]
labels are limited to 63 chars and resources are not. 

So searching for a component with a deployment label matching a resource name can lead to failures when the resource name and namespace exceed 63 chars. Change the mapping to use labels with the selectors.

issue is in deployments playbook
```
    - name: Get the Components
      k8s_info:
        kind: Component
        api_version: lb.nginx.com/v1alpha1
        namespace: "{{ lookup_namespace | default('') }}"
        label_selectors:
          - "deployment = {{ meta.name ~ '.' ~ meta.namespace }}"
      register: component
```
